### PR TITLE
restored 3 second delay on frame1 mouseover

### PR DESCRIPTION
**Pull request by lschatzkin**

### CODE REVIEW

**Comment by mfb** [comment]
We could consider making this a bit more complex: Start the 3 second timeout immediately, before mouseover. After 3 seconds, if mouseover was already triggered, or if mouseover is triggered after this point, then switch.  That way there is no waiting after the mouseover unless you're within the first 3 seconds.

**Comment by lschatzkin** [comment]
We only want a 3 sec. timeout on mouseover. If a user clicks anywhere on the screen, we want the switch to be immediate. Also, if they click on nothing it switches in 8 secs.

What do you see as the advantage of changing the mouseover animation as you suggest?

**Comment by mfb** [comment]
My personal opinion - I'm fine for this commit to go in as-is.

But I thought some folks wanted it to switch on mouseover after 3 seconds - i.e. no waiting beyond 3 seconds.  If not then never mind :)

**Comment by lschatzkin** [comment]
So what your saying is that if someone doesn't mouseover right away, they may wait more than 3 seconds? I'll point this out to Hugh &activism and see what he thinks. The latest feedback we've gotten is that things were too fast, so we'll see if things are now too slow.

**Comment by mfb** [comment]
Yes if someone stares at it for 4 seconds, then mouses over, it moves 3 seconds later @ 7 seconds.

I personally think that's fine! so feel free to ignore my comments here

**Comment by lschatzkin** [comment]
It's a good point though, I'll ask ... it's very specific as it is, so what's one more specificity?

**Comment by mfb** [comment]
side note... for this kind of bike shedding it probably makes sense to do UX testing w/ folks who've never seen the popup before.  because we have to gauge how long it takes a new user to get the joke (+ also avoid tab-closing level of user frustration if it ends up being used on a site that doesn't have an EFFy audience... :)

**Comment by lschatzkin** [comment]
Yes,  that's my understanding that's what Hugh did yesterday with activism, although I imagine some of them had seen the modal before.  But also, that's why it'll great when we get a UX designer.

**Pull request merged**
